# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(170, 120, 651, 651))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_02 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_02.setEnabled(False)
        self.pushButton_02.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_02.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_02.setStyleSheet("")
        self.pushButton_02.setText("")
        self.pushButton_02.setFlat(True)
        self.pushButton_02.setObjectName("pushButton_02")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton_02)
        self.gridLayout.addWidget(self.pushButton_02, 0, 2, 1, 1)
        self.pushButton_03 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_03.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_03.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_03.setStyleSheet("")
        self.pushButton_03.setText("")
        self.pushButton_03.setFlat(True)
        self.pushButton_03.setObjectName("pushButton_03")
        self.buttonGroup.addButton(self.pushButton_03)
        self.gridLayout.addWidget(self.pushButton_03, 0, 3, 1, 1)
        self.pushButton_00 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_00.setEnabled(False)
        self.pushButton_00.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_00.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_00.setStyleSheet("")
        self.pushButton_00.setText("")
        self.pushButton_00.setFlat(True)
        self.pushButton_00.setObjectName("pushButton_00")
        self.buttonGroup.addButton(self.pushButton_00)
        self.gridLayout.addWidget(self.pushButton_00, 0, 0, 1, 1)
        self.pushButton_01 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_01.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_01.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_01.setStyleSheet("")
        self.pushButton_01.setText("")
        self.pushButton_01.setFlat(True)
        self.pushButton_01.setObjectName("pushButton_01")
        self.buttonGroup.addButton(self.pushButton_01)
        self.gridLayout.addWidget(self.pushButton_01, 0, 1, 1, 1)
        self.pushButton_76 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_76.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_76.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_76.setStyleSheet("")
        self.pushButton_76.setText("")
        self.pushButton_76.setFlat(True)
        self.pushButton_76.setObjectName("pushButton_76")
        self.buttonGroup.addButton(self.pushButton_76)
        self.gridLayout.addWidget(self.pushButton_76, 7, 6, 1, 1)
        self.pushButton_77 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_77.setEnabled(False)
        self.pushButton_77.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_77.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_77.setStyleSheet("")
        self.pushButton_77.setText("")
        self.pushButton_77.setFlat(True)
        self.pushButton_77.setObjectName("pushButton_77")
        self.buttonGroup.addButton(self.pushButton_77)
        self.gridLayout.addWidget(self.pushButton_77, 7, 7, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_40.setEnabled(False)
        self.pushButton_40.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_40.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_40.setStyleSheet("")
        self.pushButton_40.setText("")
        self.pushButton_40.setFlat(True)
        self.pushButton_40.setObjectName("pushButton_40")
        self.buttonGroup.addButton(self.pushButton_40)
        self.gridLayout.addWidget(self.pushButton_40, 4, 0, 1, 1)
        self.pushButton_75 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_75.setEnabled(False)
        self.pushButton_75.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_75.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_75.setStyleSheet("")
        self.pushButton_75.setText("")
        self.pushButton_75.setFlat(True)
        self.pushButton_75.setObjectName("pushButton_75")
        self.buttonGroup.addButton(self.pushButton_75)
        self.gridLayout.addWidget(self.pushButton_75, 7, 5, 1, 1)
        self.pushButton_74 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_74.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_74.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_74.setStyleSheet("")
        self.pushButton_74.setText("")
        self.pushButton_74.setFlat(True)
        self.pushButton_74.setObjectName("pushButton_74")
        self.buttonGroup.addButton(self.pushButton_74)
        self.gridLayout.addWidget(self.pushButton_74, 7, 4, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_37.setEnabled(False)
        self.pushButton_37.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_37.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_37.setStyleSheet("")
        self.pushButton_37.setText("")
        self.pushButton_37.setFlat(True)
        self.pushButton_37.setObjectName("pushButton_37")
        self.buttonGroup.addButton(self.pushButton_37)
        self.gridLayout.addWidget(self.pushButton_37, 3, 7, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_42.setEnabled(False)
        self.pushButton_42.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_42.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_42.setStyleSheet("")
        self.pushButton_42.setText("")
        self.pushButton_42.setFlat(True)
        self.pushButton_42.setObjectName("pushButton_42")
        self.buttonGroup.addButton(self.pushButton_42)
        self.gridLayout.addWidget(self.pushButton_42, 4, 2, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_30.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_30.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_30.setStyleSheet("")
        self.pushButton_30.setText("")
        self.pushButton_30.setFlat(True)
        self.pushButton_30.setObjectName("pushButton_30")
        self.buttonGroup.addButton(self.pushButton_30)
        self.gridLayout.addWidget(self.pushButton_30, 3, 0, 1, 1)
        self.pushButton_73 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_73.setEnabled(False)
        self.pushButton_73.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_73.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_73.setStyleSheet("")
        self.pushButton_73.setText("")
        self.pushButton_73.setFlat(True)
        self.pushButton_73.setObjectName("pushButton_73")
        self.buttonGroup.addButton(self.pushButton_73)
        self.gridLayout.addWidget(self.pushButton_73, 7, 3, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_47.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_47.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_47.setStyleSheet("")
        self.pushButton_47.setText("")
        self.pushButton_47.setFlat(True)
        self.pushButton_47.setObjectName("pushButton_47")
        self.buttonGroup.addButton(self.pushButton_47)
        self.gridLayout.addWidget(self.pushButton_47, 4, 7, 1, 1)
        self.pushButton_72 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_72.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_72.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_72.setStyleSheet("")
        self.pushButton_72.setText("")
        self.pushButton_72.setFlat(True)
        self.pushButton_72.setObjectName("pushButton_72")
        self.buttonGroup.addButton(self.pushButton_72)
        self.gridLayout.addWidget(self.pushButton_72, 7, 2, 1, 1)
        self.pushButton_71 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_71.setEnabled(False)
        self.pushButton_71.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_71.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_71.setStyleSheet("")
        self.pushButton_71.setText("")
        self.pushButton_71.setFlat(True)
        self.pushButton_71.setObjectName("pushButton_71")
        self.buttonGroup.addButton(self.pushButton_71)
        self.gridLayout.addWidget(self.pushButton_71, 7, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setEnabled(False)
        self.pushButton_13.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_13.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_13.setStyleSheet("")
        self.pushButton_13.setText("")
        self.pushButton_13.setFlat(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.buttonGroup.addButton(self.pushButton_13)
        self.gridLayout.addWidget(self.pushButton_13, 1, 3, 1, 1)
        self.pushButton_46 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_46.setEnabled(False)
        self.pushButton_46.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_46.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_46.setStyleSheet("")
        self.pushButton_46.setText("")
        self.pushButton_46.setFlat(True)
        self.pushButton_46.setObjectName("pushButton_46")
        self.buttonGroup.addButton(self.pushButton_46)
        self.gridLayout.addWidget(self.pushButton_46, 4, 6, 1, 1)
        self.pushButton_04 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_04.setEnabled(False)
        self.pushButton_04.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_04.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_04.setStyleSheet("")
        self.pushButton_04.setText("")
        self.pushButton_04.setFlat(True)
        self.pushButton_04.setObjectName("pushButton_04")
        self.buttonGroup.addButton(self.pushButton_04)
        self.gridLayout.addWidget(self.pushButton_04, 0, 4, 1, 1)
        self.pushButton_05 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_05.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_05.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_05.setStyleSheet("")
        self.pushButton_05.setText("")
        self.pushButton_05.setFlat(True)
        self.pushButton_05.setObjectName("pushButton_05")
        self.buttonGroup.addButton(self.pushButton_05)
        self.gridLayout.addWidget(self.pushButton_05, 0, 5, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_21.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_21.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_21.setStyleSheet("")
        self.pushButton_21.setText("")
        self.pushButton_21.setFlat(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.buttonGroup.addButton(self.pushButton_21)
        self.gridLayout.addWidget(self.pushButton_21, 2, 1, 1, 1)
        self.pushButton_70 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_70.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_70.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_70.setStyleSheet("")
        self.pushButton_70.setText("")
        self.pushButton_70.setFlat(True)
        self.pushButton_70.setObjectName("pushButton_70")
        self.buttonGroup.addButton(self.pushButton_70)
        self.gridLayout.addWidget(self.pushButton_70, 7, 0, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_34.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_34.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_34.setStyleSheet("")
        self.pushButton_34.setText("")
        self.pushButton_34.setFlat(True)
        self.pushButton_34.setObjectName("pushButton_34")
        self.buttonGroup.addButton(self.pushButton_34)
        self.gridLayout.addWidget(self.pushButton_34, 3, 4, 1, 1)
        self.pushButton_35 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_35.setEnabled(False)
        self.pushButton_35.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_35.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_35.setStyleSheet("")
        self.pushButton_35.setText("")
        self.pushButton_35.setFlat(True)
        self.pushButton_35.setObjectName("pushButton_35")
        self.buttonGroup.addButton(self.pushButton_35)
        self.gridLayout.addWidget(self.pushButton_35, 3, 5, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_14.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_14.setStyleSheet("")
        self.pushButton_14.setText("")
        self.pushButton_14.setFlat(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.buttonGroup.addButton(self.pushButton_14)
        self.gridLayout.addWidget(self.pushButton_14, 1, 4, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setEnabled(False)
        self.pushButton_15.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_15.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_15.setStyleSheet("")
        self.pushButton_15.setText("")
        self.pushButton_15.setFlat(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.buttonGroup.addButton(self.pushButton_15)
        self.gridLayout.addWidget(self.pushButton_15, 1, 5, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_36.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_36.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_36.setStyleSheet("")
        self.pushButton_36.setText("")
        self.pushButton_36.setFlat(True)
        self.pushButton_36.setObjectName("pushButton_36")
        self.buttonGroup.addButton(self.pushButton_36)
        self.gridLayout.addWidget(self.pushButton_36, 3, 6, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_44.setEnabled(False)
        self.pushButton_44.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_44.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_44.setStyleSheet("")
        self.pushButton_44.setText("")
        self.pushButton_44.setFlat(True)
        self.pushButton_44.setObjectName("pushButton_44")
        self.buttonGroup.addButton(self.pushButton_44)
        self.gridLayout.addWidget(self.pushButton_44, 4, 4, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_33.setEnabled(False)
        self.pushButton_33.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_33.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_33.setStyleSheet("")
        self.pushButton_33.setText("")
        self.pushButton_33.setFlat(True)
        self.pushButton_33.setObjectName("pushButton_33")
        self.buttonGroup.addButton(self.pushButton_33)
        self.gridLayout.addWidget(self.pushButton_33, 3, 3, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_32.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_32.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_32.setStyleSheet("")
        self.pushButton_32.setText("")
        self.pushButton_32.setFlat(True)
        self.pushButton_32.setObjectName("pushButton_32")
        self.buttonGroup.addButton(self.pushButton_32)
        self.gridLayout.addWidget(self.pushButton_32, 3, 2, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_31.setEnabled(False)
        self.pushButton_31.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_31.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_31.setStyleSheet("")
        self.pushButton_31.setText("")
        self.pushButton_31.setFlat(True)
        self.pushButton_31.setObjectName("pushButton_31")
        self.buttonGroup.addButton(self.pushButton_31)
        self.gridLayout.addWidget(self.pushButton_31, 3, 1, 1, 1)
        self.pushButton_07 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_07.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_07.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_07.setStyleSheet("")
        self.pushButton_07.setText("")
        self.pushButton_07.setFlat(True)
        self.pushButton_07.setObjectName("pushButton_07")
        self.buttonGroup.addButton(self.pushButton_07)
        self.gridLayout.addWidget(self.pushButton_07, 0, 7, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setEnabled(False)
        self.pushButton_11.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_11.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_11.setStyleSheet("")
        self.pushButton_11.setText("")
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.buttonGroup.addButton(self.pushButton_11)
        self.gridLayout.addWidget(self.pushButton_11, 1, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_12.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_12.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_12.setStyleSheet("")
        self.pushButton_12.setText("")
        self.pushButton_12.setFlat(True)
        self.pushButton_12.setObjectName("pushButton_12")
        self.buttonGroup.addButton(self.pushButton_12)
        self.gridLayout.addWidget(self.pushButton_12, 1, 2, 1, 1)
        self.pushButton_52 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_52.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_52.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_52.setStyleSheet("")
        self.pushButton_52.setText("")
        self.pushButton_52.setFlat(True)
        self.pushButton_52.setObjectName("pushButton_52")
        self.buttonGroup.addButton(self.pushButton_52)
        self.gridLayout.addWidget(self.pushButton_52, 5, 2, 1, 1)
        self.pushButton_56 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_56.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_56.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_56.setStyleSheet("")
        self.pushButton_56.setText("")
        self.pushButton_56.setFlat(True)
        self.pushButton_56.setObjectName("pushButton_56")
        self.buttonGroup.addButton(self.pushButton_56)
        self.gridLayout.addWidget(self.pushButton_56, 5, 6, 1, 1)
        self.pushButton_54 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_54.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_54.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_54.setStyleSheet("")
        self.pushButton_54.setText("")
        self.pushButton_54.setFlat(True)
        self.pushButton_54.setObjectName("pushButton_54")
        self.buttonGroup.addButton(self.pushButton_54)
        self.gridLayout.addWidget(self.pushButton_54, 5, 4, 1, 1)
        self.pushButton_53 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_53.setEnabled(False)
        self.pushButton_53.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_53.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_53.setStyleSheet("")
        self.pushButton_53.setText("")
        self.pushButton_53.setFlat(True)
        self.pushButton_53.setObjectName("pushButton_53")
        self.buttonGroup.addButton(self.pushButton_53)
        self.gridLayout.addWidget(self.pushButton_53, 5, 3, 1, 1)
        self.pushButton_55 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_55.setEnabled(False)
        self.pushButton_55.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_55.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_55.setStyleSheet("")
        self.pushButton_55.setText("")
        self.pushButton_55.setFlat(True)
        self.pushButton_55.setObjectName("pushButton_55")
        self.buttonGroup.addButton(self.pushButton_55)
        self.gridLayout.addWidget(self.pushButton_55, 5, 5, 1, 1)
        self.pushButton_57 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_57.setEnabled(False)
        self.pushButton_57.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_57.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_57.setStyleSheet("")
        self.pushButton_57.setText("")
        self.pushButton_57.setFlat(True)
        self.pushButton_57.setObjectName("pushButton_57")
        self.buttonGroup.addButton(self.pushButton_57)
        self.gridLayout.addWidget(self.pushButton_57, 5, 7, 1, 1)
        self.pushButton_50 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_50.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_50.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_50.setStyleSheet("")
        self.pushButton_50.setText("")
        self.pushButton_50.setFlat(True)
        self.pushButton_50.setObjectName("pushButton_50")
        self.buttonGroup.addButton(self.pushButton_50)
        self.gridLayout.addWidget(self.pushButton_50, 5, 0, 1, 1)
        self.pushButton_51 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_51.setEnabled(False)
        self.pushButton_51.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_51.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_51.setStyleSheet("")
        self.pushButton_51.setText("")
        self.pushButton_51.setFlat(True)
        self.pushButton_51.setObjectName("pushButton_51")
        self.buttonGroup.addButton(self.pushButton_51)
        self.gridLayout.addWidget(self.pushButton_51, 5, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_10.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_10.setStyleSheet("")
        self.pushButton_10.setText("")
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.buttonGroup.addButton(self.pushButton_10)
        self.gridLayout.addWidget(self.pushButton_10, 1, 0, 1, 1)
        self.pushButton_06 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_06.setEnabled(False)
        self.pushButton_06.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_06.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_06.setStyleSheet("")
        self.pushButton_06.setText("")
        self.pushButton_06.setFlat(True)
        self.pushButton_06.setObjectName("pushButton_06")
        self.buttonGroup.addButton(self.pushButton_06)
        self.gridLayout.addWidget(self.pushButton_06, 0, 6, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_41.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_41.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_41.setStyleSheet("")
        self.pushButton_41.setText("")
        self.pushButton_41.setFlat(True)
        self.pushButton_41.setObjectName("pushButton_41")
        self.buttonGroup.addButton(self.pushButton_41)
        self.gridLayout.addWidget(self.pushButton_41, 4, 1, 1, 1)
        self.pushButton_43 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_43.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_43.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_43.setStyleSheet("")
        self.pushButton_43.setText("")
        self.pushButton_43.setFlat(True)
        self.pushButton_43.setObjectName("pushButton_43")
        self.buttonGroup.addButton(self.pushButton_43)
        self.gridLayout.addWidget(self.pushButton_43, 4, 3, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_25.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_25.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_25.setStyleSheet("")
        self.pushButton_25.setText("")
        self.pushButton_25.setFlat(True)
        self.pushButton_25.setObjectName("pushButton_25")
        self.buttonGroup.addButton(self.pushButton_25)
        self.gridLayout.addWidget(self.pushButton_25, 2, 5, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_16.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_16.setStyleSheet("")
        self.pushButton_16.setText("")
        self.pushButton_16.setFlat(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.buttonGroup.addButton(self.pushButton_16)
        self.gridLayout.addWidget(self.pushButton_16, 1, 6, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_23.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_23.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_23.setStyleSheet("")
        self.pushButton_23.setText("")
        self.pushButton_23.setFlat(True)
        self.pushButton_23.setObjectName("pushButton_23")
        self.buttonGroup.addButton(self.pushButton_23)
        self.gridLayout.addWidget(self.pushButton_23, 2, 3, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_26.setEnabled(False)
        self.pushButton_26.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_26.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_26.setStyleSheet("")
        self.pushButton_26.setText("")
        self.pushButton_26.setFlat(True)
        self.pushButton_26.setObjectName("pushButton_26")
        self.buttonGroup.addButton(self.pushButton_26)
        self.gridLayout.addWidget(self.pushButton_26, 2, 6, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_22.setEnabled(False)
        self.pushButton_22.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_22.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_22.setStyleSheet("")
        self.pushButton_22.setText("")
        self.pushButton_22.setFlat(True)
        self.pushButton_22.setObjectName("pushButton_22")
        self.buttonGroup.addButton(self.pushButton_22)
        self.gridLayout.addWidget(self.pushButton_22, 2, 2, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_24.setEnabled(False)
        self.pushButton_24.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_24.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_24.setStyleSheet("")
        self.pushButton_24.setText("")
        self.pushButton_24.setFlat(True)
        self.pushButton_24.setObjectName("pushButton_24")
        self.buttonGroup.addButton(self.pushButton_24)
        self.gridLayout.addWidget(self.pushButton_24, 2, 4, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_17.setEnabled(False)
        self.pushButton_17.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_17.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_17.setStyleSheet("")
        self.pushButton_17.setText("")
        self.pushButton_17.setFlat(True)
        self.pushButton_17.setObjectName("pushButton_17")
        self.buttonGroup.addButton(self.pushButton_17)
        self.gridLayout.addWidget(self.pushButton_17, 1, 7, 1, 1)
        self.pushButton_45 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_45.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_45.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_45.setStyleSheet("")
        self.pushButton_45.setText("")
        self.pushButton_45.setFlat(True)
        self.pushButton_45.setObjectName("pushButton_45")
        self.buttonGroup.addButton(self.pushButton_45)
        self.gridLayout.addWidget(self.pushButton_45, 4, 5, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_20.setEnabled(False)
        self.pushButton_20.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_20.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_20.setStyleSheet("")
        self.pushButton_20.setText("")
        self.pushButton_20.setFlat(True)
        self.pushButton_20.setObjectName("pushButton_20")
        self.buttonGroup.addButton(self.pushButton_20)
        self.gridLayout.addWidget(self.pushButton_20, 2, 0, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_27.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_27.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_27.setStyleSheet("")
        self.pushButton_27.setText("")
        self.pushButton_27.setFlat(True)
        self.pushButton_27.setObjectName("pushButton_27")
        self.buttonGroup.addButton(self.pushButton_27)
        self.gridLayout.addWidget(self.pushButton_27, 2, 7, 1, 1)
        self.pushButton_64 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_64.setEnabled(False)
        self.pushButton_64.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_64.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_64.setStyleSheet("")
        self.pushButton_64.setText("")
        self.pushButton_64.setFlat(True)
        self.pushButton_64.setObjectName("pushButton_64")
        self.buttonGroup.addButton(self.pushButton_64)
        self.gridLayout.addWidget(self.pushButton_64, 6, 4, 1, 1)
        self.pushButton_60 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_60.setEnabled(False)
        self.pushButton_60.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_60.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_60.setStyleSheet("")
        self.pushButton_60.setText("")
        self.pushButton_60.setFlat(True)
        self.pushButton_60.setObjectName("pushButton_60")
        self.buttonGroup.addButton(self.pushButton_60)
        self.gridLayout.addWidget(self.pushButton_60, 6, 0, 1, 1)
        self.pushButton_66 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_66.setEnabled(False)
        self.pushButton_66.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_66.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_66.setStyleSheet("")
        self.pushButton_66.setText("")
        self.pushButton_66.setFlat(True)
        self.pushButton_66.setObjectName("pushButton_66")
        self.buttonGroup.addButton(self.pushButton_66)
        self.gridLayout.addWidget(self.pushButton_66, 6, 6, 1, 1)
        self.pushButton_63 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_63.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_63.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_63.setStyleSheet("")
        self.pushButton_63.setText("")
        self.pushButton_63.setFlat(True)
        self.pushButton_63.setObjectName("pushButton_63")
        self.buttonGroup.addButton(self.pushButton_63)
        self.gridLayout.addWidget(self.pushButton_63, 6, 3, 1, 1)
        self.pushButton_61 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_61.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_61.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_61.setStyleSheet("")
        self.pushButton_61.setText("")
        self.pushButton_61.setFlat(True)
        self.pushButton_61.setObjectName("pushButton_61")
        self.buttonGroup.addButton(self.pushButton_61)
        self.gridLayout.addWidget(self.pushButton_61, 6, 1, 1, 1)
        self.pushButton_62 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_62.setEnabled(False)
        self.pushButton_62.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_62.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_62.setStyleSheet("")
        self.pushButton_62.setText("")
        self.pushButton_62.setFlat(True)
        self.pushButton_62.setObjectName("pushButton_62")
        self.buttonGroup.addButton(self.pushButton_62)
        self.gridLayout.addWidget(self.pushButton_62, 6, 2, 1, 1)
        self.pushButton_65 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_65.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_65.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_65.setStyleSheet("")
        self.pushButton_65.setText("")
        self.pushButton_65.setFlat(True)
        self.pushButton_65.setObjectName("pushButton_65")
        self.buttonGroup.addButton(self.pushButton_65)
        self.gridLayout.addWidget(self.pushButton_65, 6, 5, 1, 1)
        self.pushButton_67 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_67.setMinimumSize(QtCore.QSize(80, 80))
        self.pushButton_67.setMaximumSize(QtCore.QSize(80, 80))
        self.pushButton_67.setStyleSheet("")
        self.pushButton_67.setText("")
        self.pushButton_67.setFlat(True)
        self.pushButton_67.setObjectName("pushButton_67")
        self.buttonGroup.addButton(self.pushButton_67)
        self.gridLayout.addWidget(self.pushButton_67, 6, 7, 1, 1)
        self.new_gameButton = QtWidgets.QPushButton(self.centralwidget)
        self.new_gameButton.setGeometry(QtCore.QRect(70, 30, 91, 31))
        self.new_gameButton.setObjectName("new_gameButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(620, 30, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.new_gameButton.setText(_translate("MainWindow", "New Game"))

